### PR TITLE
Add more README content

### PR DESCRIPTION
**Pull request by mojo9492**
Add README.md outline. Includes problem statement/overview,  contents, description, installation, usage headers.  Add Description body

### CODE REVIEW

**Review by DebugBridge — APPROVED** [review]
Looks good.

**Review by gitjerezt — APPROVED** [review]
Good to go.

**Review by DebugBridge — COMMENTED** [review]
gtg

**Review by DebugBridge — APPROVED** [review]
good

**Review by hectorhcuevas — APPROVED** [review]

**Pull request merged**
